import { MetadataRoute } from "next";

const routes = [
  "",
  "ai-background-remover",
  "ai-image-enhancer",
  "ai-product-photo-editor",
  "ai-product-photo-enhancer",
  "amazon-image-editor",
  "amazon-image-requirements",
  "amazon-listing-image-creator",
  "amazon-product-images",
  "amazon-product-photo-editor",
  "amazon-white-background-tool",
  "background-remover-for-ecommerce",
  "catalog-image-editor",
  "ebay-product-photo-editor",
  "ecommerce-image-editor",
  "ecommerce-photo-editor",
  "ecommerce-image-enhancer",
  "etsy-background-remover",
  "etsy-image-editor",
  "etsy-listing-photo-editor",
  "etsy-product-photo-editor",
  "free-background-remover",
  "hd-product-photo-editor",
  "high-resolution-product-images",
  "image-quality-enhancer",
  "increase-image-resolution",
  "marketplace-image-editor",
  "online-product-photo-editor",
  "photo-quality-enhancer",
  "png-background-remover",
  "product-image-cleaner",
  "product-image-optimization",
  "product-image-optimizer",
  "product-image-resizer",
  "product-image-upscaler",
  "product-listing-image-editor",
  "product-photo-background-remover",
  "product-photo-cleanup",
  "product-photo-cropper",
  "product-photo-editor",
  "product-photo-enhancement-tool",
  "product-photo-retouching",
  "product-photo-size-editor",
  "professional-product-image-editor",
  "remove-background-from-image",
  "remove-background-online",
  "shopify-background-remover",
  "shopify-image-editor",
  "shopify-product-photo-editor",
  "transparent-background-maker",
  "white-background-generator",
  "white-background-image",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: `https://productreadyapp.com${route ? `/${route}` : ""}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: route === "" ? 1 : 0.8,
  }));
}